codecov:
  # no notifications set up
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 1
  round: nearest
  # thresholds for red to green color coding
  range: '10...100'

  status:
    project:
      default:
        # compares coverage to the base branch
        target: auto
        # if it drops by 25%, send a fail status
        threshhold: 25
        # only send statuses for prs, not all commits
        base: pr
    patch: no
    changes: no

comment: off
